### ISSUE TITLE
T4-Downloading Repositories

### ISSUE THREAD

**Issue by ZachAndrews98** [GatorGauge/GatorGauge#1]
Getting all of the repositories that need to be analyzed.

**Comment by ZachAndrews98** [comment]
Added functionality to read default variables from a config file so that no source code has to be changed. Information on how to run it is in the readme (formatted kinda bad but don't judge). Make sure you put a github token in the config file or else the program won't run.

**Comment by millinj2** [comment]
Just waiting for the token from Kapfhammer

**Comment by ZachAndrews98** [comment]
Got token.
