### ISSUE TITLE
T4-Repl for GatorGauge

### ISSUE THREAD

**Issue by burrowss** [GatorGauge/GatorGauge#19]
Would a repl be useful for this program so that it continuously gets feedback? Responses are appreciated

**Comment by ZachAndrews98** [comment]
I believe it would be a good feature to have, especially if the user forgets to input a necessary flag or something else that causes the system to crash they don't have to completely restart the program.

**Comment by jonathanwmendez** [comment]
Team 3 agrees that we should use a repl for this program.

**Comment by sutterj** [comment]
I started work on a REPL.  The question that I have is how does github_clone_all use the arguments that the user enters?  What does the user have to enter each time in order to clone the repos?  Can they leave out arguments and allow the program to still run (ie. they already put in the token, but they want to add the repos to a different destination).

**Comment by ZachAndrews98** [comment]
github_clone_all uses the arguments passed in (project to download, prefix to narrow down downloads, token, directory to output to (defaults to a directory with the project's name in the main directory)). The user has to enter into the terminal, the token and the name of the project at minimum (assuming these are not entered into the config.ini) the other flags either have a default or are not necessary. If you have any questions (or if this jumble of words confuses you) let me know.

**Comment by sutterj** [comment]
When using the REPL, we won't need parse_args.py.  One of the REPL commands should be help, but I am not sure exactly how you would like to do that.  I could make a file to display the help statements when help is typed in the REPL.  What do you guys think?

**Comment by ZachAndrews98** [comment]
I think that we should do that. Something similar to what was implemented with Accelegator I believe would be best. That way we can show what each command is and go into detail about how the user can use those commands.
