### ISSUE TITLE
Team 3 - Count Commits

### ISSUE THREAD

**Issue by lylet-AC** [GatorGauge/GatorGauge#2]
Extract the number of commits for each repository.

**Comment by TravisThomasAC** [comment]
(https://files.slack.com/files-pri/T6UNMCREU-F81TL4745/img_20171116_160650.jpg)

**Comment by TravisThomasAC** [comment]
![](https://files.slack.com/files-pri/T6UNMCREU-F81PJ7MD1/image_uploaded_from_ios.jpg)

**Comment by TravisThomasAC** [comment]
(https://files.slack.com/files-pri/T6UNMCREU-F81PJ7MD1/image_uploaded_from_ios.jpg)


This is what we want the parser to return

**Comment by TravisThomasAC** [comment]
dulwich parse function
https://github.com/jelmer/dulwich/blob/master/dulwich/objects.py
