### ISSUE TITLE
import_commits_as_string.py does not actually write to a string

### ISSUE THREAD

**Issue by lylet-AC** [GatorGauge/GatorGauge#24]
So I kept having an issue with the sys.stdout being called by the porcelain.py in the dulwich package.  This means that the program doesn't return the list of commits, but rather prints them out directly.  My goal was to try to capture the output before it went on to the terminal.  I believe the program is doing this as running it will not give the typical list of commits as it would, but rather returns no output at all.

So it's clear that the sys.stdout redirection is working somehow, but I cannot import this information as a string for some reason.

**Comment by burrowss** [comment]
Is this issue still happening in your current pull request?

**Comment by lylet-AC** [comment]
Nope, that's what that pull request fixes!
