### ISSUE TITLE
Team 3 - Generate List of Commits

### ISSUE THREAD

**Issue by lylet-AC** [GatorGauge/GatorGauge#3]
Parse through the commits obtained with porcelain.  Return a list of tuples that contains commit information:

(insertions, deletions, timestamp, github emoji, keyword, number_of_commits)

**Comment by karolvargas** [comment]
The only way I can use gensim to do NLP on the commit messages is with a list of lists so maybe a good way to generate the list of lists would be to create a loop that iterates through the string and after every sentence would be one list and after every space would be another list so each sentence would return as a list of words and all the sentences could be returned as a list of sentences

**Comment by karolvargas** [comment]
this is what we had done on previous labs such as accelegator so if you look through the branch which is creating the list of responses there are some good examples there
