### ISSUE TITLE
Team 1 Return summary statistics for comments

### ISSUE THREAD

**Issue by dillam** [GatorGauge/GatorGauge#31]
This task is to return different statistics about the comments. These will include average number of commented lines per program, ratio of lines of comments from lines of code, and average length of multi-line comments.

**Comment by mariakimheinert** [comment]
@dillam solving the task of calculating the ratio of lines of comments from lines of code would benefit from talking to team 2 who are doing the java source code parsing.

**Comment by shafferz** [comment]
When you say "average number of commented lines per program," you mean relative to all of the programs in a given user's repository, yes? 

Also, to avoid the inflation of statistics, if we assume that the multi-line comments are written in the Javadoc format, should we exclude certain tags in counting things like "length" of multi-line comments? For example, if a student is particularly apt with Javadoc and uses tags such as `@author` or `@version`, where the information isn't necessarily indicative of the quality (or description) of the method, should we include those in our analysis?

**Comment by shafferz** [comment]
Follow-up from our discussion in lab: regardless of any NLP analysis we perform on the comments, the question of the value of the actual hard numbers in terms of statistical context still remains. We can count the number of comments, single-line or multi-line. It is also worth noting that the Javadoc comments are also multi-line comments, they just add "fluff" space and tags that, for the purpose of statistical relevance and sentiment analysis. 

Other than just counting the comments, what statistics are valuable to us? We talked about particularly long multi-line comments (average length?) possibly being indicative of the complexity of the code written. If that is the case, what is more important: the overall average length of the comments across all students for any given assignment, or the average of the averages of each individual student's approach to the assignment? There are pros and cons to both (an average of averages, for example, might help counter the issue of individual students who write particularly long comments skewing the data). I believe the general consensus that we came to in lab is that most of these numbers, aside from being easy to collect, may be contextually meaningless. 

I'm willing to also see if any research has been done in the way of this already. That is to say, if anyone has researched the actual relationship between comments and lines of code in terms of what the statistics mean. @gkapfham also mentioned in lab that the program can serve to show the students where they have an unacceptable imbalance of comments to code (too few comments to code indicating poorly commented code).

**Comment by colezAC** [comment]
Should we be looking to see if the comments follow the commenting standard for javadoc?

**Comment by delgrecoj** [comment]
Checking for styleguide standards would be something GatorGrader handles already (through `checkstyle`, I believe)... I'm not seeing the usefulness of checking for it on this project.

**Comment by delgrecoj** [comment]
I'm apparently going to be writing some helper functions for use by other teams down the line... we already have the ratio functions and extraction functions working, and the other statistics are mostly just tracking the counts, so no new functionality to add there.

**Comment by mariakimheinert** [comment]
Closing because addressed by merge of `parse_comments.py`.
