### ISSUE TITLE
Team 1 Documentation and test cases

### ISSUE THREAD

**Issue by dillam** [GatorGauge/GatorGauge#33]
This task is for creating documentation and test cases for the code that we have created. This is also where people should put a technical description of their functions so that we can write test cases.

**Comment by eltmanm** [comment]
unless someone else is already doing it, i can take care of the major documentation for how we're analyzing comments and what we're looking for.

**Comment by eltmanm** [comment]
definition of completion is updated so that documentation and test cases will accompany the source code as the source code is completed. This issue is now obsolete.
