### ISSUE TITLE
Team 3 - Process Commit Messages with NLP

### ISSUE THREAD

**Issue by lylet-AC** [GatorGauge/GatorGauge#4]
Use NLP to find common keywords and topics for each commit.

**Comment by karolvargas** [comment]
tokens from expected list of lists created as well as corpus dictionary from messages created

**Comment by karolvargas** [comment]
creating function to parse emojis and create counter to keep track of what emojis were used for each repository throughout the semester

**Comment by karolvargas** [comment]
https://github.com/alexmick/emoji-data-python/blob/master/README.md

**Comment by jonathanwmendez** [comment]
https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by karolvargas** [comment]
using parser to find all emoticon objects by their unicode

**Comment by geerc** [comment]
https://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by karolvargas** [comment]
Need to figure out how to fix error with parser using re.iter function not registering the emojis in the string

**Comment by karolvargas** [comment]
closing issue #4
