### ISSUE TITLE
Team 1 Topical Analysis for JavaDoc comments

### ISSUE THREAD

**Issue by dillam** [GatorGauge/GatorGauge#44]

**Comment by delgrecoj** [comment]
This might be complicated slightly by keywords from the JavaDoc standard appearing regularly... for example, `@author` and the other markers aren't really topics.  Those keywords might be best trimmed away from the comments before they are fed into the NLP functions.

**Comment by eltmanm** [comment]
https://en.wikipedia.org/wiki/Javadoc

**Comment by delgrecoj** [comment]
I'm apparently going to be writing something to remove the keywords, to avoid biasing the topic analysis.

**Comment by delgrecoj** [comment]
https://en.wikipedia.org/wiki/Javadoc has a list of the keywords.

**Comment by mariakimheinert** [comment]
@eltmanm will be creating function to remove the Javadoc tags from a list of comment strings.

**Comment by eltmanm** [comment]
it's completed and awaiting pull request acceptance
