### ISSUE TITLE
Team 1: Implement get_all_comments function

### ISSUE THREAD

**Issue by mariakimheinert** [GatorGauge/GatorGauge#56]
`get_all_comments` should take in a list of strings that are Java programs and output a tuple of lists, which contain all singleline, multiline, and Javadoc comments from all of the Java program. This will be used for the `get_avg_sentiment` function.
```
comment_tuple = (["singleline comment 1", "singleline comment 2"], 
["multiline comment 1", "multiline comment 2"], 
["Javadoc comment 1", "Javadoc comment 2"])
```

**Comment by delgrecoj** [comment]
This has been implemented and tested... included in pull request #78.
