### ISSUE TITLE
Team 1: Implement analyze_comments function

### ISSUE THREAD

**Issue by mariakimheinert** [GatorGauge/GatorGauge#57]
`analyze_comments` should leverage the outputs of `get_java_strings()`, `get_avg_nums_of_comments()`, `get_ratios_of_comments()`, `get_avg_sentiment()` to produce a cohesive analysis output that is printed to the console and appended to the LDA HTML file. It should also call `gensim_analysis()` on a list of Javadoc strings (can use the output of `get_all_comments()`) to produce a LDA visualization.

**Comment by dillam** [comment]
@yeeunmariakim I am unable to find any of the functions you mention in the description in this repository. Are they still being built, or am I just not looking in the right places?

**Comment by mariakimheinert** [comment]
@dillam they are being implemented now by our team members.

**Comment by delgrecoj** [comment]
Mostly complete implementation of this in PR #83... mainly waiting for answers on the `gensim_analysis` function, and will de-duplicate some of the code when other helper functions get merged into master.

**Comment by delgrecoj** [comment]
(apparently correct, but not yet executed implementation now merged into master... can't run it until other parts of the system are merged in and integrated... does now utilize the various helper functions, though)

**Comment by delgrecoj** [comment]
merged, thus closing.
