### ISSUE TITLE
T4-Parse through markdown files

### ISSUE THREAD

**Issue by toccinAC** [GatorGauge/GatorGauge#9]
We need to parse through the markdown files and put the words into a list. We need to decide if it will be a list of list or list of tuples.

**Comment by toccinAC** [comment]
List of lists would be my preference.

**Comment by burrowss** [comment]
https://pypi.python.org/pypi/mistune

**Comment by burrowss** [comment]
http://mistune.readthedocs.io/en/latest/

**Comment by burrowss** [comment]
So we want to be ignoring:
\# and words following it for the headers
\> for block quotes
\*, \+, \-, 1. for lists
\*, _, \**, \__, for emphasis in sentences
\` for code

Overall:
\\   backslash
\`   backtick
\*   asterisk
\_   underscore
\{}  curly braces
\[]  square brackets
\()  parentheses
\#   hash mark
\+   plus sign
\-   minus sign (hyphen)
\.   dot
\!   exclamation mark

**Comment by ZachAndrews98** [comment]
I got this working, it returns a list of lists that is made up of sentences and removes "\n" and "#" headers. Anything else that needs to be removed (ie special characters) can also be done if needed, just let me know.

**Comment by ZachAndrews98** [comment]
System works, returns list of lists, closing issue.
