### ISSUE TITLE
Loop inside of get function

### ISSUE THREAD

**Issue by lylet-AC** [GatorGauge/GatorGauge#99]
Typing N doesn't do anything other than place you right back into the same loop.

![problem](https://user-images.githubusercontent.com/31486141/33906897-57010948-df51-11e7-9bf1-8b08c7f7f820.png)

Edit: After "changing the name" to lab5, I now downloaded a repo for lab5.  Why is it asking me to change the name if I'm just pulling?

**Comment by ZachAndrews98** [comment]
The project name is required for the user to download the repositories, it is the name of the organization that the repositories are in. If there is no project name then the program will not know where to look so it asks the user to input the project name.
